package mirrors

// MirrorList é uma lista de mirrors do Debian Linux
var MirrorList = [...]string{
	"http://ftp.am.debian.org/debian/",
	"http://ftp.au.debian.org/debian/",
	"http://ftp.at.debian.org/debian/",
	"http://ftp.by.debian.org/debian/",
	"http://ftp.be.debian.org/debian/",
	"http://ftp.br.debian.org/debian/",
	"http://ftp.bg.debian.org/debian/",
	"http://ftp.ca.debian.org/debian/",
	"http://ftp.cl.debian.org/debian/",
	"http://ftp2.cn.debian.org/debian/",
	"http://ftp.cn.debian.org/debian/",
	"http://ftp.hr.debian.org/debian/",
	"http://ftp.cz.debian.org/debian/",
	"http://ftp.dk.debian.org/debian/",
	"http://ftp.sv.debian.org/debian/",
	"http://ftp.ee.debian.org/debian/",
	"http://ftp.fr.debian.org/debian/",
	"http://ftp2.de.debian.org/debian/",
	"http://ftp.de.debian.org/debian/",
	"http://ftp.gr.debian.org/debian/",
	"http://ftp.hk.debian.org/debian/",
	"http://ftp.hu.debian.org/debian/",
	"http://ftp.is.debian.org/debian/",
	"http://ftp.it.debian.org/debian/",
	"http://ftp.jp.debian.org/debian/",
	"http://ftp.kr.debian.org/debian/",
	"http://ftp.lt.debian.org/debian/",
	"http://ftp.mx.debian.org/debian/",
	"http://ftp.md.debian.org/debian/",
	"http://ftp.nl.debian.org/debian/",
}
